name: Deploy Next.js App

on:
  push:
    branches:
      - main  # 监听 main 分支推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install --frozen-lockfile

      # 4. 构建 Next.js
      - name: Build Next.js
        run: npm run build

      # 5. 打包 Docker 镜像
      - name: Build Docker image
        run: docker build -t tango-ui-cw .

      # 6. 部署到远程服务器 via SSH
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            docker stop tango-ui-cw || true
            docker rm tango-ui-cw || true
            docker run -d --name tango-ui-cw -p 80:3000 tango-ui-cw
