name: Deploy Next.js App

on:
  push:
    branches:
      - main  # 监听 main 分支推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. 安装依赖 & 构建（本地跑一次保证能过）
      - name: Build Next.js
        run: |
          npm install --frozen-lockfile
          npm run build

      # 4. 部署到远程服务器
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /root/tango
            git reset --hard
            git pull origin main
            docker stop tango-ui-doc || true
            docker rm tango-ui-doc || true
            docker build -t tango-ui-doc .
            docker run -d --name tango-ui-doc -p 80:3000 tango-ui-doc
